version: '3'
services:
  webserver:
    image: nginx:latest
    container_name: webserver
    ports:
      - "80:80"
    volumes:
      - ./src:/usr/share/nginx/html
      # - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf