version: '3'
services:
  etl:
    image: nginx:latest
    container_name: etl
    ports:
      - "81:80"
    volumes:
      - ./src:/usr/share/nginx/html
      # - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf